export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const CLEAR_BURGER_BUILDER_STATE = 'CLEAR_BURGER_BUILDER_STATE';


export const PURCHASE_BURGER_START = 'PURCHASE_BURGER_START';
export const PURCHASE_BURGER_SUCCESS = 'PURCHASE_BURGER_SUCCESS';
export const PURCHASE_BURGER_FAIL = 'PURCHASE_BURGER_FAIL';
export const ORDER_SUCCESS_INIT = 'ORDER_SUCCESS_INIT';
export const CLEAR_ORDER_STATE = 'CLEAR_ORDER_STATE';
